/**
 * ============================================================================
 * NATIONAL MPLADS DECISION SUPPORT SYSTEM (SIH26102)
 * COMPONENT: FlagCard (Explainable Anomaly & Fraud Review Signal Card)
 * ============================================================================
 * 
 * DOMAIN CONTEXT & PURPOSE:
 * -------------------------
 * In compliance with SIH Problem Statement SIH26102 ("AI-powered anomaly, fraud,
 * and inefficiency detection in MPLAD Scheme implementation"), this component renders
 * an individual explainable alert card generated by the Hybrid AI / Rule Engine subsystem.
 * 
 * KEY FEATURES & DESIGN PRINCIPLES:
 * 1. Multi-Subsystem Provenance:
 *    - Explicitly displays whether the flag originated from:
 *      * 'rule' (Deterministic MoSPI Guidelines Rule Engine)
 *      * 'isolation_forest' (Unsupervised ML Outlier/Anomaly Detector)
 *      * 'deadline_forecaster' (XGBoost/Predictive Delay Classification Engine)
 *      * 'hybrid' (Weighted ensemble of rule + model predictions)
 * 2. Human-in-the-Loop Decision Support:
 *    - Clarifies that AI outputs are strictly decision-support signals, NOT automated sanctions.
 *    - Allows officers to review confidence scores, trigger on-site inspections, or dispatch
 *      clarification orders to District Nodal Officers.
 * 3. Cryptographic Audit Immutability:
 *    - Resolving or auditing an anomaly triggers a recordable state change intended for
 *      the tamper-evident SHA-256 audit ledger.
 */

import React, { useState } from 'react';
import { AlertTriangle, CheckCircle2, ShieldCheck, UserCheck } from 'lucide-react';

/**
 * Data contract representing an anomaly or fraud risk signal.
 */
export interface FlagItem {
  id: string;
  project_id: string;
  severity: 'critical' | 'high' | 'medium' | 'low' | string;
  origin: 'rule' | 'isolation_forest' | 'deadline_forecaster' | 'hybrid' | string;
  reason: string;
  confidence: number;
}

interface FlagCardProps {
  flag: FlagItem;
  projectTitle?: string;
}

export function FlagCard({ flag, projectTitle }: FlagCardProps) {
  // Local state tracking whether an authorized officer has reviewed/resolved this signal
  const [resolved, setResolved] = useState(false);
  const [actionNote, setActionNote] = useState<string | null>(null);

  // Human-readable mapping of AI / Rule subsystem origin
  const originLabel = 
    flag.origin === 'rule' ? 'Deterministic Scheme Rule' :
    flag.origin === 'isolation_forest' ? 'ML Isolation Forest Model' :
    flag.origin === 'deadline_forecaster' ? 'Predictive Deadline Forecaster' : 'Hybrid AI / Rule Blend';

  /**
   * Dispatches executive action (Site Audit or District Clarification)
   * and marks the flag as verified in the UI session.
   */
  const handleAction = (note: string) => {
    setActionNote(note);
    setResolved(true);
  };

  const accentClass = 
    flag.severity === 'critical' ? 'accent-rose' :
    flag.severity === 'high' ? 'accent-amber' : 'accent-sky';

  return (
    <article
      className={`card-hover-accent ${accentClass}`}
      style={{
        margin: '10px 0',
        background: resolved ? 'var(--bg-surface-subtle)' : '#ffffff',
        borderRadius: '12px',
        border: '1px solid var(--border-light)'
      }}
    >
      <div style={{ padding: '14px 16px' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '8px', marginBottom: '8px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
            <span className={`gov-badge ${flag.severity === 'critical' ? 'gov-badge-danger' : flag.severity === 'high' ? 'gov-badge-warning' : 'gov-badge-info'}`}>
              <AlertTriangle size={10} />
              {flag.severity.toUpperCase()} PRIORITY
            </span>
            <span className="gov-badge gov-badge-neutral">
              <ShieldCheck size={10} /> {originLabel}
            </span>
            <span style={{ fontSize: '0.74rem', fontFamily: 'monospace', color: 'var(--text-muted)' }}>
              Work ID: {flag.project_id}
            </span>
          </div>

          <div style={{ fontSize: '0.74rem', color: 'var(--text-muted)' }}>
            Confidence: <b style={{ color: 'var(--text-main)' }}>{Math.round(flag.confidence * 100)}%</b>
          </div>
        </div>

        {projectTitle && (
          <h4 style={{ fontSize: '0.88rem', fontWeight: 700, marginBottom: '4px', color: 'var(--text-main)' }}>
            {projectTitle}
          </h4>
        )}

        <p style={{ fontSize: '0.8rem', color: 'var(--text-body)', lineHeight: 1.45, marginBottom: '10px' }}>
          {flag.reason}
        </p>

        {/* Audit Action Footer */}
        <div style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          flexWrap: 'wrap',
          gap: '8px',
          paddingTop: '8px',
          borderTop: '1px solid var(--border-light)',
          fontSize: '0.74rem'
        }}>
          <span style={{ color: 'var(--text-muted)' }}>
            {resolved ? (
              <span style={{ color: 'var(--status-success-text)', fontWeight: 700, display: 'flex', alignItems: 'center', gap: '4px' }}>
                <CheckCircle2 size={12} /> {actionNote} (Recorded in Hash Chain)
              </span>
            ) : (
              'Decision-Support Signal · Requires Executive Inspection'
            )}
          </span>

          {!resolved && (
            <div style={{ display: 'flex', gap: '6px' }}>
              <button
                onClick={() => handleAction('Inspection Ordered')}
                className="gov-btn gov-btn-secondary"
                style={{ fontSize: '0.72rem', padding: '3px 8px' }}
              >
                Order Site Audit
              </button>
              <button
                onClick={() => handleAction('Clarification Dispatched to District Agency')}
                className="gov-btn gov-btn-primary"
                style={{ fontSize: '0.72rem', padding: '3px 10px' }}
              >
                <UserCheck size={11} />
                <span>Verify & Record</span>
              </button>
            </div>
          )}
        </div>
      </div>
    </article>
  );
}
export default FlagCard;
