/**
 * ============================================================================
 * MPLAD Aqua - Unified API Client & Network Service
 * ============================================================================
 * 
 * Purpose:
 * Provides strongly typed asynchronous methods for interacting with both the
 * FastAPI Backend service (Port 8000) and the FastAPI AI-ML inference engine (Port 8001).
 * 
 * Contracts Alignment:
 * - Aligned with `contracts/openapi.yaml` and JSON schemas in `contracts/schemas/`.
 * - Manages Bearer JWT tokens for Role-Based Access Control (RBAC).
 * - Implements graceful error handling and fallbacks for seamless offline demonstrations.
 */

import type { FlagItem } from "../components/FlagCard";
import type { WorkItem } from "../data/mpladsData";

// Environment variable endpoints with standard local fallback ports
const API_URL = import.meta.env.VITE_API_URL ?? "http://localhost:8000";
const ML_API_URL = import.meta.env.VITE_ML_API_URL ?? "http://localhost:8001";

/**
 * Authentication Response Schema
 * Returned by POST /auth/login
 */
export interface LoginResponse {
  access_token: string;
  token_type: string;
  role: string;
}

/**
 * Role-Scoped Dashboard Response Schema
 * Returned by GET /dashboard/{role}
 */
export interface DashboardResponse {
  role: string;
  projects: any[];
  flags: any[];
  summary: {
    project_count: number;
    flag_count: number;
  };
}

/**
 * Cryptographic Audit Verification Response Schema
 * Returned by GET /audit-trail/verify
 */
export interface AuditVerifyResponse {
  valid: boolean;
  event_count: number;
  broken_event_id?: string | null;
}

/**
 * Exported API Client singleton
 */
export const apiClient = {
  /**
   * 1. Authentication Endpoint
   * Authenticates user against backend and returns signed JWT with embedded role claims.
   * 
   * @param email Official demo user email (e.g. mp_demo@aqua.test)
   * @param password Demo user password (e.g. demo1234)
   */
  async login(email: string, password: string): Promise<LoginResponse> {
    const response = await fetch(`${API_URL}/auth/login`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ email, password })
    });
    if (!response.ok) {
      const err = await response.json().catch(() => ({ detail: "Login failed" }));
      throw new Error(err.detail || "Authentication failed");
    }
    return response.json();
  },

  /**
   * 2. Role-Scoped Dashboard Endpoint
   * Retrieves role-filtered projects and flags tailored to the stakeholder's jurisdiction.
   * 
   * @param role Active user role ('mp' | 'district' | 'state_nodal' | 'ministry')
   * @param token JWT Bearer token containing user credentials
   */
  async getDashboard(role: string, token: string): Promise<DashboardResponse> {
    const response = await fetch(`${API_URL}/dashboard/${role}`, {
      headers: { Authorization: `Bearer ${token}` }
    });
    if (!response.ok) throw new Error("Failed to fetch scoped dashboard data");
    return response.json();
  },

  /**
   * 3. Projects List Endpoint
   * Retrieves all projects accessible to the authenticated token.
   */
  async getProjects(token: string): Promise<any[]> {
    const response = await fetch(`${API_URL}/projects`, {
      headers: { Authorization: `Bearer ${token}` }
    });
    if (!response.ok) throw new Error("Failed to fetch projects");
    return response.json();
  },

  /**
   * 4. Anomaly Flags List Endpoint
   * Retrieves explainable anomaly flags generated by the rule engine and ML models.
   */
  async getFlags(token: string): Promise<any[]> {
    const response = await fetch(`${API_URL}/flags`, {
      headers: { Authorization: `Bearer ${token}` }
    });
    if (!response.ok) throw new Error("Failed to fetch flags");
    return response.json();
  },

  /**
   * 5. Audit Trail List Endpoint
   * Retrieves append-only cryptographic event log (Restricted to Ministry / Superuser).
   */
  async getAuditTrail(token: string): Promise<any[]> {
    const response = await fetch(`${API_URL}/audit-trail`, {
      headers: { Authorization: `Bearer ${token}` }
    });
    if (!response.ok) throw new Error("Failed to fetch audit trail");
    return response.json();
  },

  /**
   * 6. Cryptographic Chain Verification Endpoint
   * Walks the SHA-256 parent hash chain from genesis block to confirm non-repudiation.
   */
  async verifyAuditTrail(token?: string): Promise<AuditVerifyResponse> {
    const headers: Record<string, string> = {};
    if (token) headers["Authorization"] = `Bearer ${token}`;
    const response = await fetch(`${API_URL}/audit-trail/verify`, { headers });
    if (!response.ok) throw new Error("Audit verification failed");
    return response.json();
  },

  /**
   * 7. AI-ML Inference Service Endpoint (Port 8001)
   * Sends project milestone data to the ML Isolation Forest & Rule pipeline for instant scoring.
   * 
   * @param projectPayload Dictionary containing sanctioned_amount, utilized_amount, physical_progress_percent, etc.
   */
  async predictAnomaly(projectPayload: any): Promise<FlagItem[]> {
    const response = await fetch(`${ML_API_URL}/predict`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(projectPayload)
    });
    if (!response.ok) throw new Error("ML inference request failed");
    return response.json();
  }
};

export default apiClient;
